export const HOME = '/home'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const PESTAÑA = '/pestaña'
export const INICIO = '/inicio'
export const EXAMEN1 = '/examen1'
export const EXAMEN2 = '/examen2'
export const EXAMEN3 = '/examen3'